### ISSUE TITLE
Padding seems broken in docs mode for HTML framework project as of 4.2.0

### ISSUE THREAD

**Issue by tylersticka** [rbardini/storybook-addon-paddings#28]
When updating to `4.2.0`, all of our stories displayed errors complaining of a duplicate decorator and a missing `fn` for the `withPaddings` decorator.

Viewing the source, it seemed like the need to manually enable the decorator was removed, so we removed that from our `preview.js` file. This fixed the errors, but in docs mode all of the padding from our stories was set to `0`.

<img width="430" alt="Screen Shot 2021-07-09 at 10 07 32 AM" src="https://user-images.githubusercontent.com/69633/125113426-81606e80-e09d-11eb-8b40-05d2f00fb759.png">

Here's a live example: https://v-next--cloudfour-patterns.netlify.app/?path=/docs/components-button--button-element

What's interesting is that if I peer into the styles of the element I'd expect to have padding, I see the following inline styles:

```css
      .sb-show-main {
        margin: 0;
        padding: 1em !important;
        transition: padding .3s;
      }

      .sb-show-main .innerZoomElementWrapper > div {
        border-width: 0 !important;
      }
```

I wouldn't expect `.sb-show-main` to be the selector here, based on this portion of this project's source: https://github.com/rbardini/storybook-addon-paddings/blob/33a4bf6fa7af7d9989e9df157ddee66ea27cc10f/src/index.tsx#L27-L29

I also tried adding the decorator again manually using the updated export name (`WithPaddings`). This restored Storybook's default padding but appears to have broken the add-on (I see duplicate errors in the console).

Our project is public if it's helpful to try running it locally: https://github.com/cloudfour/cloudfour.com-patterns
